## Split keyboards
## https://zmk.dev/docs/config/system#split-keyboards
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_INPUT_LISTENER=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# ## Track words per minute
# CONFIG_ZMK_WPM=y

## ZMK Studio
## https://zmk.dev/docs/features/studio
CONFIG_ZMK_STUDIO=n
## https://zmk.dev/docs/config/studio
CONFIG_ZMK_STUDIO_LOCKING=y
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=y
CONFIG_ZMK_STUDIO_TRANSPORT_BLE_PREF_LATENCY=5

## Pointing
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y

## Dongle Build Missing Keystrokes troubleshooting
## Tried, but no luck:
CONFIG_ZMK_USB=y
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_SPLIT_BLE_PERIPHERAL_COUNT=2

## Under test:

## Possible fixes for missing keystrokes when using the dongle build.